import './js/refs.js';
import './js/artists-api';
import './js/render-function.js';
import './js/storage.js';
import './js/modal';
import './js/handlers.js';
import './js/feedback.js';
import './js/header.js';
import './js/modal-feedback.js';